services:

  mssql:
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      SITECORE_ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
      ACCEPT_EULA: "Y"
      SQL_SERVER: mssql
    volumes:
      - .\docker\data\mssql:C:\data
    deploy:
      resources:
        limits:
          cpus: 3
          memory: 3GB

  cm:
    ports:
      - "44080:80"
    environment:
      Sitecore_ConnectionStrings_Core: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=sa;Password=${SQL_SA_PASSWORD}
      Sitecore_ConnectionStrings_Security: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=sa;Password=${SQL_SA_PASSWORD}
      Sitecore_ConnectionStrings_Master: Data Source=mssql;Initial Catalog=Sitecore.Master;User ID=sa;Password=${SQL_SA_PASSWORD}
      Sitecore_ConnectionStrings_Web: Data Source=mssql;Initial Catalog=Sitecore.Web;User ID=sa;Password=${SQL_SA_PASSWORD}
      Sitecore_ConnectionStrings_ExperienceForms: Data Source=mssql;Initial Catalog=Sitecore.ExperienceForms;User ID=sa;Password=${SQL_SA_PASSWORD}
      Sitecore_ConnectionStrings_Solr.Search: http://solr:8983/solr
      Sitecore_AppSettings_Telerik.AsyncUpload.ConfigurationEncryptionKey: ${TELERIK_ENCRYPTION_KEY}
      Sitecore_AppSettings_Telerik.Upload.ConfigurationHashKey: ${TELERIK_ENCRYPTION_KEY}
      Sitecore_AppSettings_Telerik.Web.UI.DialogParametersEncryptionKey: ${TELERIK_ENCRYPTION_KEY}
      MEDIA_REQUEST_PROTECTION_SHARED_SECRET: ${MEDIA_REQUEST_PROTECTION_SHARED_SECRET}
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
      SOLR_CORE_PREFIX_NAME: ${SOLR_CORE_PREFIX_NAME}
    volumes:
      - .\docker\deploy\platform:C:\deploy
      - ${HOST_LICENSE_FOLDER}:C:\license
    entrypoint: powershell.exe -Command "& C:\tools\entrypoints\iis\Development.ps1"
    depends_on:
      mssql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 3
          memory: 2GB